### PR TITLE
Update uuid dependency.

### PR DESCRIPTION
**Pull request by JanezStupar**
Update uuid dependency.
Update SDK to include 3.0.0.

### CODE REVIEW

**Review by DauRagnarokas — APPROVED** [review]

**Review by DauRagnarokas — APPROVED** [review]

**Comment by JanezStupar** [comment]
@DauRagnarokas would you be kind enough to merge this PR pls. You approved it, but then I don-t have permissions to merge it.

**Comment by raccoons-are-goofy** [comment]
I merged #5. Not sure if that one included changes to the SDK. If not, please go ahead and make a new PR. I'll try to get it in. Unfortunately I am no longer actively maintaining this, and will be looking for someone to take over.

**Comment by j3g** [comment]
the "reformat the code" commit is not something I agree with. I prefer original.

**Comment by JanezStupar** [comment]
Closed pull request because another PR already handles the UUID issue will create a new one.

**Comment by JanezStupar** [comment]
> the "reformat the code" commit is not something I agree with. I prefer original.

That is fine, arguably I prefer the current style too. But the change was made by `dart format .`

**Pull request closed without merging**
